### ISSUE TITLE
Formalize Plan for Selected Instrumentation Stack

### ISSUE THREAD

**Issue by dvonthenen** [thecodeteam/roadmap#175]
Based on the research and deliverables for coming up with a selected monitoring/instrumentation stack in this Issue https://github.com/codedellemc/roadmap/issues/174, we need to formalize a plan for:
- How we are going to utilize this stack
- Define the milestones and deliverables for each phase

Deliverables:  
- [x] Stand up ZOP stack POC with "full" configuration (Zipkin, Prometheus, Kubernetes instrumentations)  [Deliverable Date: 7/24]
- [x] Blog: (Part 1) How-to "Stand up ZOP stack" [Deliverable Date: 7/26]
- [x] Stand up ZOP with Persistent Storage (example using ScaleIO) [Deliverable Date: 7/31]
- [x] Blog: (Part 2) How-to ZOP with Persistent Storage (ScaleIO) [Deliverable Date: 8/2]
- [x] PR: Implement required Hooks in GoScaleio project for Prometheus Metrics. [Deliverable Date: 8/18]
- [x] PR: Implement Prometheus Metrics for ScaleIO specific to Kubernetes. [Deliverable Date: 8/25]
- [x] Blog: Implement Prometheus Metrics for ScaleIO specific to Kubernetes. [Deliverable Date: 8/25]
- [x] Implement Helm Chart for Jaeger [Deliverable Date: 9/6]
- [x] Blog: Helm Chart for Jaeger [Deliverable Date: 9/8]

Considerations:
- Open Source Summit + MesosCon NA: Week of Sept 11
- Traveling to DockerCon+OSS+MesosCon EU: Oct 13
- On-site Meeting: Week of Sept 25
- Any maintenance work relating to Mesos, Framework, etc
- CSI Instrumentation depends on formalization of CSI spec and implementation
- TBD: Mesos/DC/OS ScaleIO Framework consuming CSI (depends on Mesosphere Roadmaps/Deliverables)

**Comment by dvonthenen** [comment]
Beginning planning...

**Comment by dvonthenen** [comment]
Removing Issue https://github.com/codedellemc/roadmap/issues/180 entitled "Implement Prometheus/OpenTracing (with Zipkin? can abstract?) Instrumentation in higher level shim layer in Kubernetes"

Please see the issue for more details.

**Comment by dvonthenen** [comment]
Closing this as completed. Created a Q4 Jaeger functionality epic track additional Jaeger work.
