### ISSUE TITLE
REX-Ray 4Q17 releases

### ISSUE THREAD

**Issue by clintkitson** [thecodeteam/roadmap#197]
0.11 Feature Release - DockerCon EU  (9/17)
Board - https://github.com/codedellemc/rexray#boards?milestones=2017.10-1%232017-10-13&repos=46084622,100317726,33909634
Release Summary - https://docs.google.com/document/d/1UPm-jXM5z61gbI2-5DlqhjOFmnFbcUCBo6XbLq-Np6w/edit?usp=sharing

- [x] Docker
  - [x] Docker->CSI Southbound Adapter codedellemc/rexray#1037
  - [x] New managed plug-ins codedellemc/rexray#817
  - [x] Enhanced configuration options for managed plug-ins codedellemc/rexray#1043, codedellemc/rexray#933
  - [ ] Swarm review

- [x] Community asks codedellemc/rexray#1050
- [x] Low hanging fruit (issues) codedellemc/rexray#913, codedellemc/rexray#955, codedellemc/rexray#924, codedellemc/rexray#994

0.12.0 Feature Release - KubeCon (12/17)
https://github.com/thecodeteam/rexray#boards?milestones=2017-12.1%232017-12-05,2017.11-1%232017-11-10,2017.12-1%232017-12-05&repos=33909634,100317726

- [ ] CSI - relying on 0.1 tag
  - [x] gocsi package 
  - [x] csi-scaleio
  - [x] csi-vsphere
  - [ ] Southbound adapter update
  - [ ] csi-vfs
  - [ ] csi-blockdevices
  - [ ] csi-nfs
- [x] Bug fixes
- [x] Refactor to thecodeteam
