### ISSUE TITLE
2017Q4 Jaeger Functionality

### ISSUE THREAD

**Issue by dvonthenen** [thecodeteam/roadmap#218]
Planned Q4 Jaeger Functionality (In no particular order)
- [x] PR: Update ElasticSearch Chart to support Default Storage class and EmptyDir
- [x] PR: Jaeger Helm Chart to Support ElasticSearch
- [x] Personal Blog: Jaeger Helm Chart ElasticSearch Support
- [x] ~~PR: Add support for Jaeger sidecar deployments~~  Implemented by another user
- [x] ~~Personal Blog: Jaeger sidecar deployments support~~ Implemented by another user
