### ISSUE TITLE
2018Q1 CoreOS etcd contributions

### ISSUE THREAD

**Issue by dvonthenen** [thecodeteam/roadmap#225]
Work/tasks relating to helping out the etcd community.

Pending tasks:
- [x] Sign up for bi-weekly etcd hangout (https://github.com/coreos/etcd#community-meetings)
- [x] Read through on-boarding documentation
- [x] Setup Developer Environment
- [x] Review etcd Demo
- [x] Pick an issue or feature to work on as an intro. Will wait for community planning meeting for feedback.
